### ISSUE TITLE
Implementation issue

### ISSUE THREAD

**Issue by Krazyxx** [mthl/enki#17]
I have an implementation issue.
For you, what is the "best" version?

/* Version 1 */
std::vector<uint32_t> data;
while (pos2 != string::npos) {
	data.push_back(getValue(pos1, pos2, strGroundTexture));
	pos1 = pos2 + 1;
	pos2 = strGroundTexture.find_first_of(TYPE_SEPARATOR, pos1);
}
uint32_t *bits = (uint32_t*)data.data();
/**/

/* Version 2 */
uint32_t* bits = (uint32_t*) malloc(sizeof(uint32_t) * width * height);
unsigned i = 0;
while (pos2 != string::npos) {
	bits[i++] = getValue(pos1, pos2, strGroundTexture);
	pos1 = pos2 + 1;
	pos2 = strGroundTexture.find_first_of(TYPE_SEPARATOR, pos1);
}
/**/

**Comment by sebpouteau** [comment]
Don't use ```malloc```!

**Comment by sebpouteau** [comment]
Don't use ```c malloc```
