### ISSUE TITLE
groundTexture

### ISSUE THREAD

**Issue by nicpalard** [mthl/enki#7]
In enki, a world can have a texture to its ground, this texture is named groundTexture and is created via an image with the following piece of code
```c++
QImage image = new QImage("path/to/imageFile.png");
if(!image.isNull())
{
   uint32_t *bits = (uint32_t*)image.bits();
   GroundTexture* gt = new GroundTexture(image.width, image.height, bits);
}
World* w  = new World(w, h, gt);
```
The issue is that a GroundTexture requires an image in order to be created.
In most of the case, the world has no ground texture but it possibly can have one.

My question is for my random module, should I load a random groundTexture from of a selection of images with different types such as jpg, png, bmp etc, or should I compute bits randomly ?

**Comment by mthl** [comment]
I don't think computing the bits randomly would generate something pleasing to the eyes.  In my opinion no texture is OK.
